$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
enabledLanguageIds:
  - "*"
words:
  - composables
  - libsql
  - LIFF
  - miniflare
  - nitropack
  - nuxt
  - paralleldrive
  - pinia
  - richmenuswitch
  - rushstack
  - tsdoc
  - vuejs
  - vuetify
  - vueuse
